# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'archive_clone_sniffer_gui.ui'
#
# Created: Sat Mar 28 21:25:21 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 736)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/archiveclonesniffer.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setObjectName("tab_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_files = QtWidgets.QGridLayout()
        self.gridLayout_files.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_files.setVerticalSpacing(6)
        self.gridLayout_files.setObjectName("gridLayout_files")
        self.label_dbname = QtWidgets.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.label_dbname.setFont(font)
        self.label_dbname.setObjectName("label_dbname")
        self.gridLayout_files.addWidget(self.label_dbname, 0, 0, 1, 1)
        self.label_files = QtWidgets.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.label_files.setFont(font)
        self.label_files.setObjectName("label_files")
        self.gridLayout_files.addWidget(self.label_files, 3, 0, 1, 1)
        self.label_archive = QtWidgets.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.label_archive.setFont(font)
        self.label_archive.setObjectName("label_archive")
        self.gridLayout_files.addWidget(self.label_archive, 1, 0, 1, 1)
        self.toolSelectButton_db = QtWidgets.QToolButton(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.toolSelectButton_db.setFont(font)
        self.toolSelectButton_db.setObjectName("toolSelectButton_db")
        self.gridLayout_files.addWidget(self.toolSelectButton_db, 0, 2, 1, 1)
        self.label_archive2 = QtWidgets.QLabel(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.label_archive2.setFont(font)
        self.label_archive2.setObjectName("label_archive2")
        self.gridLayout_files.addWidget(self.label_archive2, 2, 0, 1, 1)
        self.lineEdit_archive = QtWidgets.QLineEdit(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.lineEdit_archive.setFont(font)
        self.lineEdit_archive.setObjectName("lineEdit_archive")
        self.gridLayout_files.addWidget(self.lineEdit_archive, 1, 1, 1, 1)
        self.lineEdit_files = QtWidgets.QLineEdit(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.lineEdit_files.setFont(font)
        self.lineEdit_files.setObjectName("lineEdit_files")
        self.gridLayout_files.addWidget(self.lineEdit_files, 3, 1, 1, 1)
        self.toolSelectButton_archive = QtWidgets.QToolButton(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.toolSelectButton_archive.setFont(font)
        self.toolSelectButton_archive.setObjectName("toolSelectButton_archive")
        self.gridLayout_files.addWidget(self.toolSelectButton_archive, 1, 2, 1, 1)
        self.lineEdit_archive2 = QtWidgets.QLineEdit(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.lineEdit_archive2.setFont(font)
        self.lineEdit_archive2.setObjectName("lineEdit_archive2")
        self.gridLayout_files.addWidget(self.lineEdit_archive2, 2, 1, 1, 1)
        self.lineEdit_dbname = QtWidgets.QLineEdit(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.lineEdit_dbname.setFont(font)
        self.lineEdit_dbname.setObjectName("lineEdit_dbname")
        self.gridLayout_files.addWidget(self.lineEdit_dbname, 0, 1, 1, 1)
        self.toolSelectButton_archive2 = QtWidgets.QToolButton(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.toolSelectButton_archive2.setFont(font)
        self.toolSelectButton_archive2.setObjectName("toolSelectButton_archive2")
        self.gridLayout_files.addWidget(self.toolSelectButton_archive2, 2, 2, 1, 1)
        self.toolSelectButton_file = QtWidgets.QToolButton(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.toolSelectButton_file.setFont(font)
        self.toolSelectButton_file.setObjectName("toolSelectButton_file")
        self.gridLayout_files.addWidget(self.toolSelectButton_file, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_files)
        spacerItem = QtWidgets.QSpacerItem(811, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_operations = QtWidgets.QGridLayout()
        self.gridLayout_operations.setObjectName("gridLayout_operations")
        spacerItem1 = QtWidgets.QSpacerItem(114, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_operations.addItem(spacerItem1, 8, 0, 1, 1)
        self.checkBox_forceAdd = QtWidgets.QCheckBox(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.checkBox_forceAdd.setFont(font)
        self.checkBox_forceAdd.setObjectName("checkBox_forceAdd")
        self.gridLayout_operations.addWidget(self.checkBox_forceAdd, 5, 3, 1, 1)
        self.radioButton_add = QtWidgets.QRadioButton(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.radioButton_add.setFont(font)
        self.radioButton_add.setObjectName("radioButton_add")
        self.buttonGroup_ops = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_ops.setObjectName("buttonGroup_ops")
        self.buttonGroup_ops.addButton(self.radioButton_add)
        self.gridLayout_operations.addWidget(self.radioButton_add, 5, 1, 1, 1)
        self.radioButton_list = QtWidgets.QRadioButton(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.radioButton_list.setFont(font)
        self.radioButton_list.setObjectName("radioButton_list")
        self.buttonGroup_ops.addButton(self.radioButton_list)
        self.gridLayout_operations.addWidget(self.radioButton_list, 6, 3, 1, 1)
        self.radioButton_reset = QtWidgets.QRadioButton(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.radioButton_reset.setFont(font)
        self.radioButton_reset.setObjectName("radioButton_reset")
        self.buttonGroup_ops.addButton(self.radioButton_reset)
        self.gridLayout_operations.addWidget(self.radioButton_reset, 7, 3, 1, 1)
        self.radioButton_remove = QtWidgets.QRadioButton(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.radioButton_remove.setFont(font)
        self.radioButton_remove.setObjectName("radioButton_remove")
        self.buttonGroup_ops.addButton(self.radioButton_remove)
        self.gridLayout_operations.addWidget(self.radioButton_remove, 7, 1, 1, 1)
        self.radioButton_compare = QtWidgets.QRadioButton(self.tab_main)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.radioButton_compare.setFont(font)
        self.radioButton_compare.setObjectName("radioButton_compare")
        self.buttonGroup_ops.addButton(self.radioButton_compare)
        self.gridLayout_operations.addWidget(self.radioButton_compare, 6, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_operations.addItem(spacerItem2, 6, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_operations.addItem(spacerItem3, 6, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_operations)
        self.tabWidget.addTab(self.tab_main, "")
        self.tab_sql = QtWidgets.QWidget()
        self.tab_sql.setObjectName("tab_sql")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_sql)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit_sql = QtWidgets.QPlainTextEdit(self.tab_sql)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_sql.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_sql.setSizePolicy(sizePolicy)
        self.plainTextEdit_sql.setTabChangesFocus(True)
        self.plainTextEdit_sql.setObjectName("plainTextEdit_sql")
        self.horizontalLayout.addWidget(self.plainTextEdit_sql)
        self.pushButton_viewSchema = QtWidgets.QPushButton(self.tab_sql)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        self.pushButton_viewSchema.setFont(font)
        self.pushButton_viewSchema.setObjectName("pushButton_viewSchema")
        self.horizontalLayout.addWidget(self.pushButton_viewSchema)
        self.tabWidget.addTab(self.tab_sql, "")
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.pushButton_exec = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_exec.sizePolicy().hasHeightForWidth())
        self.pushButton_exec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.pushButton_exec.setFont(font)
        self.pushButton_exec.setFlat(False)
        self.pushButton_exec.setObjectName("pushButton_exec")
        self.verticalLayout.addWidget(self.pushButton_exec)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.textEdit_viewport = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_viewport.sizePolicy().hasHeightForWidth())
        self.textEdit_viewport.setSizePolicy(sizePolicy)
        self.textEdit_viewport.setMaximumSize(QtCore.QSize(16777215, 1080))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.textEdit_viewport.setFont(font)
        self.textEdit_viewport.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_viewport.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_viewport.setReadOnly(True)
        self.textEdit_viewport.setObjectName("textEdit_viewport")
        self.verticalLayout.addWidget(self.textEdit_viewport)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 853, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Edit = QtWidgets.QMenu(self.menuBar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menuBar)
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.actionE_xit = QtWidgets.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.action_Clear_All_Fields = QtWidgets.QAction(MainWindow)
        self.action_Clear_All_Fields.setObjectName("action_Clear_All_Fields")
        self.action_Backup_Database = QtWidgets.QAction(MainWindow)
        self.action_Backup_Database.setObjectName("action_Backup_Database")
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Backup_Database)
        self.menu_File.addAction(self.actionE_xit)
        self.menu_Help.addAction(self.action_About)
        self.menu_Edit.addAction(self.action_Clear_All_Fields)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Edit.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_dbname, self.toolSelectButton_db)
        MainWindow.setTabOrder(self.toolSelectButton_db, self.lineEdit_archive)
        MainWindow.setTabOrder(self.lineEdit_archive, self.toolSelectButton_archive)
        MainWindow.setTabOrder(self.toolSelectButton_archive, self.lineEdit_archive2)
        MainWindow.setTabOrder(self.lineEdit_archive2, self.toolSelectButton_archive2)
        MainWindow.setTabOrder(self.toolSelectButton_archive2, self.lineEdit_files)
        MainWindow.setTabOrder(self.lineEdit_files, self.toolSelectButton_file)
        MainWindow.setTabOrder(self.toolSelectButton_file, self.radioButton_add)
        MainWindow.setTabOrder(self.radioButton_add, self.checkBox_forceAdd)
        MainWindow.setTabOrder(self.checkBox_forceAdd, self.radioButton_compare)
        MainWindow.setTabOrder(self.radioButton_compare, self.radioButton_list)
        MainWindow.setTabOrder(self.radioButton_list, self.radioButton_remove)
        MainWindow.setTabOrder(self.radioButton_remove, self.radioButton_reset)
        MainWindow.setTabOrder(self.radioButton_reset, self.plainTextEdit_sql)
        MainWindow.setTabOrder(self.plainTextEdit_sql, self.pushButton_viewSchema)
        MainWindow.setTabOrder(self.pushButton_viewSchema, self.pushButton_exec)
        MainWindow.setTabOrder(self.pushButton_exec, self.textEdit_viewport)
        MainWindow.setTabOrder(self.textEdit_viewport, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archive Clone Sniffer"))
        self.label_dbname.setText(_translate("MainWindow", "SQLite Database"))
        self.label_files.setText(_translate("MainWindow", "File(s)"))
        self.label_archive.setText(_translate("MainWindow", "Archive"))
        self.toolSelectButton_db.setText(_translate("MainWindow", "..."))
        self.label_archive2.setText(_translate("MainWindow", "Archive 2"))
        self.lineEdit_archive.setToolTip(_translate("MainWindow", "Shortcut: Ctrl+2"))
        self.lineEdit_files.setToolTip(_translate("MainWindow", "Shortcut: Ctrl+4"))
        self.toolSelectButton_archive.setText(_translate("MainWindow", "..."))
        self.lineEdit_archive2.setToolTip(_translate("MainWindow", "Shortcut: Ctrl+3"))
        self.lineEdit_dbname.setToolTip(_translate("MainWindow", "Shortcut: Ctrl+1"))
        self.toolSelectButton_archive2.setText(_translate("MainWindow", "..."))
        self.toolSelectButton_file.setText(_translate("MainWindow", "..."))
        self.checkBox_forceAdd.setStatusTip(_translate("MainWindow", "Force add files in archive even if they are already present in the database"))
        self.checkBox_forceAdd.setText(_translate("MainWindow", "F&orce add"))
        self.radioButton_add.setStatusTip(_translate("MainWindow", "Add files in archive to database (individual files cannot be added)"))
        self.radioButton_add.setText(_translate("MainWindow", "&Add archive to database"))
        self.radioButton_list.setStatusTip(_translate("MainWindow", "Lists database contents which match archive name (or, Lists files in archive if no database given)"))
        self.radioButton_list.setText(_translate("MainWindow", "&List archive files"))
        self.radioButton_reset.setStatusTip(_translate("MainWindow", "Remove all contents of database and reset its schema"))
        self.radioButton_reset.setText(_translate("MainWindow", "Reset DB"))
        self.radioButton_remove.setStatusTip(_translate("MainWindow", "Remove entires from database, which are associated with the given archive name"))
        self.radioButton_remove.setText(_translate("MainWindow", "&Remove from DB"))
        self.radioButton_compare.setStatusTip(_translate("MainWindow", "List matching files in order of priority:  (1) database vs. archive (2) database vs. file(s) (3) archive vs. archive2 (4) archive vs. file(s)"))
        self.radioButton_compare.setText(_translate("MainWindow", "&Compare Database / Archives /  File(s)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), _translate("MainWindow", "Main Ops"))
        self.plainTextEdit_sql.setToolTip(_translate("MainWindow", "Shortcut: Ctrl+5"))
        self.plainTextEdit_sql.setPlaceholderText(_translate("MainWindow", "Type your SQL query here"))
        self.pushButton_viewSchema.setText(_translate("MainWindow", "&View DB Schema"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sql), _translate("MainWindow", "SQL Query"))
        self.pushButton_exec.setText(_translate("MainWindow", "E&xecute"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.action_About.setShortcut(_translate("MainWindow", "F1"))
        self.action_New.setText(_translate("MainWindow", "&New"))
        self.action_New.setToolTip(_translate("MainWindow", "Create a new Sqlite database"))
        self.action_New.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.actionE_xit.setText(_translate("MainWindow", "E&xit"))
        self.actionE_xit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_Clear_All_Fields.setText(_translate("MainWindow", "&Clear All Fields"))
        self.action_Clear_All_Fields.setShortcut(_translate("MainWindow", "Ctrl+Alt+C"))
        self.action_Backup_Database.setText(_translate("MainWindow", "&Backup Database"))

from . import acs_resources_rc
